### ISSUE TITLE
Carriage returns in manifest break tool

### ISSUE THREAD

**Issue by birm** [SBU-BMI/uploadHeatmaps#7]
If the manifest file has \r, then it messes up the urls.
```
{"host":"quip-pathdb","port":80,"path":"/idlookup/PDAC_Technical_Pilot/VTRPDAC_T
est/PC4068/PC4068_BL3_00\r?_format=json"}```

Reading manifest file.
_http_client.js:127
      throw new TypeError('Request path contains unescaped characters');
      ^

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at request (http.js:38:10)
    at Object.get (http.js:42:13)
    at Interface.myInterface.on.on (/usr/local/bin/convert_heatmaps.js:175:20)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at ReadStream.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at ReadStream.emit (events.js:208:7)

**Comment by birm** [comment]
quickfixed with sed -i 's/\r$//g' manifest.csv
